# Generated by Django 4.2.7 on 2024-05-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='projects/main/', verbose_name='Main image'),
        ),
    ]
