# Generated by Django 4.2.7 on 2023-11-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_uuid_post_unique_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uuid',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=None, null=True, verbose_name='Slug'),
        ),
    ]
