# Generated by Django 4.2.7 on 2024-03-20 05:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_blogsubscriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogSubscriber',
            new_name='Subscriber',
        ),
    ]
