# Generated by Django 4.2.7 on 2023-12-04 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_url_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='projects/main/', verbose_name='Main image'),
            preserve_default=False,
        ),
    ]
